# Python Lesson 3 Practice Assignment

1. Create a dictionary where the keys are the names of months and the values are the number of days in that month. Allow a user to enter the name of a month and print the number of days in that month. Create appropriate prompts and print statements so the user knows what to do and can interpret the response.

In [4]:
months = {'Jan':31, 'Feb':28, 'March':31, 'April':30, 'May':31, 'June':30, 'July':31, 'Aug':31, 'Sept':30, 'Oct':31, 'Nov':30, 'Dec':31}

input_month = input('Enter the month: ')
print(f'{input_month} has {months[input_month]} days') if input_month in months else print('Invalid month')

Jan has 31 days


2. Using the statement that creates the dictionary that is a catalog of items (below), create another dictionary with exactly the same items and keys, but for which the values are prices as decimal numbers. Let the user type in a catalog number, then print the name of the item and its price. Prepend a dollar sign `$` to the price before printing, but don’t include the dollar sign in the dictionary.

In [12]:
catalog = {'1008':'widget', '2149':'flange', '19x5':'smoke shifter', '992':'poiuyt'}

prices = {'1008': 15.99, '2149': 9.50, '19x5': 25.75, '992': 3.99}

def get_item_info():
    catalog_number = input("Enter a catalog number: ")
    if catalog_number in catalog and catalog_number in prices:
        item_name = catalog[catalog_number]
        item_price = prices[catalog_number]
        print(f"{item_name}: ${item_price:.2f}")
    else:
        print("Invalid catalog number.")

get_item_info()


widget: $15.99


3. Modify the last program to convert the price of the selected item to euros (you may need to look up the exchange rate). Add an additional statement to print the price in euros, prepending the Unicode string for the euro sign (`\u20AC`) to the numeric price. Make the print statement work so that there is no space between the euro sign and the price.

In [13]:
catalog = {'1008': 'widget', '2149': 'flange', '19x5': 'smoke shifter', '992': 'poiuyt'}

prices = {'1008': 15.99, '2149': 9.50, '19x5': 25.75, '992': 3.99}

exchange_rate = 0.93

def get_item_info():
    catalog_number = input("Enter a catalog number: ")
    if catalog_number in catalog and catalog_number in prices:
        item_name = catalog[catalog_number]
        item_price_usd = prices[catalog_number]
        # Convert the price to euros
        item_price_eur = item_price_usd * exchange_rate
        print(f"{item_name}: ${item_price_usd:.2f}")
        # Print the price in euros with the euro sign
        print(f"{item_name}: \u20AC{item_price_eur:.2f}")
    else:
        print("Item not found in catalog.")

get_item_info()


widget: $15.99
widget: €14.87


4. Convert the catalog dictionary in problem 2 to a pandas Series. Using `.loc`, print the name of the item with catalog number `19x5`. Then, using `.iloc`, print the name of the second item in the list.

In [14]:
import pandas as pd
catalog = {'1008': 'widget', '2149': 'flange', '19x5': 'smoke shifter', '992': 'poiuyt'}

catalog_series = pd.Series(catalog)

print(catalog_series.loc['19x5'])
print(catalog_series.iloc[1])




smoke shifter
flange


5. Convert the two dictionaries in problem 2 to a pandas DataFrame using pd.DataFrame. Display the DataFrame below the cell in tabular form.


In [15]:
import pandas as pd

catalog = {'1008': 'widget', '2149': 'flange', '19x5': 'smoke shifter', '992': 'poiuyt'}
prices = {'1008': 15.99, '2149': 9.50, '19x5': 25.75, '992': 3.99}

df = pd.DataFrame({'Catalog Number': list(catalog.keys()), 'Item Name': list(catalog.values()), 'Price': list(prices.values())})

df


Catalog Number      Item Name  Price
0           1008         widget  15.99
1           2149         flange   9.50
2           19x5  smoke shifter  25.75
3            992         poiuyt   3.99

6. Using the DataFrame you just created, print the Series for the price column. Then print the Series for the catalog number 2149 row.

In [24]:
price_series = df['Price']
print(price_series)

row_2149 = df.iloc[1]

print(row_2149)


0    15.99
1     9.50
2    25.75
3     3.99
Name: Price, dtype: float64
Catalog Number      2149
Item Name         flange
Price                9.5
Name: 1, dtype: object


7. The second line of code below reads in a CSV containing climate data: the average precipitation and temperature for months the year 1879 in Mesa, Arizona. Display the first 6 rows of the DataFrame below the cell in tabular form. 

In the following code cell, print the following:
- the data for March 1879 (as a Series).
- the average temperture for July 1879.


In [33]:
import pandas as pd
climate = pd.read_csv('https://github.com/HeardLibrary/digital-scholarship/raw/master/data/codegraf/mesa_climate.csv')
print(climate.head(6))

climate = climate.set_index('month')

  month   ppt  tavg
0   Jan  92.8  12.1
1   Feb  19.1  10.1
2   Mar  18.2  11.8
3   Apr   0.0  19.2
4   May   4.1  25.0
5   Jun   0.0  28.1


In [53]:
import pandas as pd
climate = pd.read_csv('https://github.com/HeardLibrary/digital-scholarship/raw/master/data/codegraf/mesa_climate.csv')
climate = climate.set_index('month')

print('March 1879:')
print(climate.iloc[2])

print('Average temp for July 1879:' , climate.loc['Jul', 'tavg'])




March 1879:
ppt     18.2
tavg    11.8
Name: Mar, dtype: float64
Average temp for July 1879: 32.4


8. Create a list that contains the names of the days of the week. Using a `for` loop, print the days of the week.

In [61]:
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
for i in range(len(days)):
    print(days[i])
    i += 1
    

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday


9. Using a `for` loop and the `.iterrows` method, print the month abbreviation and average temperature in Mesa for each month in 1879 together on the same line. (Remember that the month abbreviation is now the index for the row.) To make the output clearer, print a header explaining what the columns are before you print the values.

In [60]:
print('Average Monthly Temperature in Mesa, AZ, 1879')
for index, row in climate.iterrows():
    print(f"{index}: {row['tavg']}")


Average Monthly Temperature in Mesa, AZ, 1879
Jan: 12.1
Feb: 10.1
Mar: 11.8
Apr: 19.2
May: 25.0
Jun: 28.1
Jul: 32.4
Aug: 32.2
Sep: 28.2
Oct: 19.5
Nov: 14.5
Dec: 8.7


10. Create a variable called `sum` and set its value to zero. Create a `for` loop that steps through each month and adds the precipitation value for each month to the `sum` variable. Recall that

```
sum += number
```

is a shortcut for

```
sum = sum + number
```

After you add up all of the values, print the value of the average precipitation for all months of the year. (Don't worry about weighting the monthly values by the length of the month.)

In [66]:
sum = 0
for index, row in climate.iterrows():
    sum += row['ppt']

print('Total precipitation for 1879:', sum)
print('Average monthly precipitation for 1879:', sum/12)




Total precipitation for 1879: 228.5
Average monthly precipitation for 1879: 19.041666666666668


11. Because pandas is designed for vectorized operations, there is an easier way to find the average precipitation for all of the months. Simply append the `.mean()` method to the precipitation column of the DataFrame. (The mean method does not require any arguments.) Print the result. Is it the same as what you got using the `for` loop?

In [68]:
average_ppt = climate['ppt'].mean()
print('Average precipitation:', average_ppt)

#Same result as the for loop out to 14 decimal places. Last decimal place is different.


Average precipitation: 19.041666666666664
